# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roobics/ball_track

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roobics/ball_track

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roobics/ball_track/CMakeFiles /home/roobics/ball_track/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roobics/ball_track/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ball_tracking

# Build rule for target.
ball_tracking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ball_tracking
.PHONY : ball_tracking

# fast build rule for target.
ball_tracking/fast:
	$(MAKE) -f CMakeFiles/ball_tracking.dir/build.make CMakeFiles/ball_tracking.dir/build
.PHONY : ball_tracking/fast

#=============================================================================
# Target rules for targets named cal_hsv

# Build rule for target.
cal_hsv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cal_hsv
.PHONY : cal_hsv

# fast build rule for target.
cal_hsv/fast:
	$(MAKE) -f CMakeFiles/cal_hsv.dir/build.make CMakeFiles/cal_hsv.dir/build
.PHONY : cal_hsv/fast

ball_detect.o: ball_detect.cpp.o

.PHONY : ball_detect.o

# target to build an object file
ball_detect.cpp.o:
	$(MAKE) -f CMakeFiles/ball_tracking.dir/build.make CMakeFiles/ball_tracking.dir/ball_detect.cpp.o
.PHONY : ball_detect.cpp.o

ball_detect.i: ball_detect.cpp.i

.PHONY : ball_detect.i

# target to preprocess a source file
ball_detect.cpp.i:
	$(MAKE) -f CMakeFiles/ball_tracking.dir/build.make CMakeFiles/ball_tracking.dir/ball_detect.cpp.i
.PHONY : ball_detect.cpp.i

ball_detect.s: ball_detect.cpp.s

.PHONY : ball_detect.s

# target to generate assembly for a file
ball_detect.cpp.s:
	$(MAKE) -f CMakeFiles/ball_tracking.dir/build.make CMakeFiles/ball_tracking.dir/ball_detect.cpp.s
.PHONY : ball_detect.cpp.s

get_hsv_threshold.o: get_hsv_threshold.cpp.o

.PHONY : get_hsv_threshold.o

# target to build an object file
get_hsv_threshold.cpp.o:
	$(MAKE) -f CMakeFiles/cal_hsv.dir/build.make CMakeFiles/cal_hsv.dir/get_hsv_threshold.cpp.o
.PHONY : get_hsv_threshold.cpp.o

get_hsv_threshold.i: get_hsv_threshold.cpp.i

.PHONY : get_hsv_threshold.i

# target to preprocess a source file
get_hsv_threshold.cpp.i:
	$(MAKE) -f CMakeFiles/cal_hsv.dir/build.make CMakeFiles/cal_hsv.dir/get_hsv_threshold.cpp.i
.PHONY : get_hsv_threshold.cpp.i

get_hsv_threshold.s: get_hsv_threshold.cpp.s

.PHONY : get_hsv_threshold.s

# target to generate assembly for a file
get_hsv_threshold.cpp.s:
	$(MAKE) -f CMakeFiles/cal_hsv.dir/build.make CMakeFiles/cal_hsv.dir/get_hsv_threshold.cpp.s
.PHONY : get_hsv_threshold.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ball_tracking"
	@echo "... rebuild_cache"
	@echo "... cal_hsv"
	@echo "... ball_detect.o"
	@echo "... ball_detect.i"
	@echo "... ball_detect.s"
	@echo "... get_hsv_threshold.o"
	@echo "... get_hsv_threshold.i"
	@echo "... get_hsv_threshold.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

